# Setup dependencies

---
- hosts: all
  # remote_user: root
  sudo: yes
  # sudo_user: name
  vars:
    vrrp_instance:
      name: mariadb
      interface: eth0
      virtual_ipaddress: 10.78.26.76
      auth_pass: 1234568
    virtual_server:
      ip_address: "10.78.26.76"
    real_server:
      ip_addresses:
        - "10.78.26.73:3306"
        - "10.78.26.74:3306"
        - "10.78.26.75:3306"
  tasks:
    - include: ./tasks/install-keepalived.yaml state=present
  handlers:
    - name: restart keepalived
      service: name=keepalived state=started
